export const theme = {
  colors: {
    background: '#0a0a0f',
    surface: '#12121a',
    primary: '#8b5cf6',
    secondary: '#6366f1',
    error: '#CF6679',
    text: '#f0f0f5',
    textSecondary: '#9d9db5',
    border: '#1e1e2e',
    success: '#4BB543',
    card: '#16161f',
  },
  fonts: {
    regular: 'GoogleSans-Regular',
    medium: 'GoogleSans-Medium',
    semiBold: 'GoogleSans-SemiBold',
    bold: 'GoogleSans-Bold',
    // Display / accent font
    display: 'GoogleSans-Regular',
    displayMedium: 'GoogleSans-Medium',
    displaySemiBold: 'GoogleSans-SemiBold',
    displayBold: 'GoogleSans-Bold',
    // display: 'PlayfairDisplay-Regular',
    // displayMedium: 'PlayfairDisplay-Medium',
    // displaySemiBold: 'PlayfairDisplay-SemiBold',
    // displayBold: 'PlayfairDisplay-Bold',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  typography: {
    h1: {
      fontSize: 32,
      fontWeight: '600' as const,
      color: '#f0f0f5',
      fontFamily: 'GoogleSans-Bold',
    },
    h2: {
      fontSize: 24,
      fontWeight: '600' as const,
      color: '#f0f0f5',
      fontFamily: 'GoogleSans-Bold',
    },
    h3: {
      fontSize: 20,
      fontWeight: '600' as const,
      color: '#f0f0f5',
      fontFamily: 'GoogleSans-SemiBold',
    },
    body: {
      fontSize: 16,
      fontWeight: 'normal' as const,
      color: '#f0f0f5',
      fontFamily: 'GoogleSans-Regular',
    },
    caption: {
      fontSize: 14,
      fontWeight: 'normal' as const,
      color: '#9d9db5',
      fontFamily: 'GoogleSans-Medium',
    },
    small: {
      fontSize: 12,
      fontWeight: 'normal' as const,
      color: '#9d9db5',
      fontFamily: 'GoogleSans-Regular',
    },
  },

  borderRadius: {
    sm: 4,
    md: 12,
    lg: 16,
    round: 9999,
  },
};
