create table if not exists public.ai_usage_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  model text not null,
  question_preview text,
  used_tool_call boolean not null default false,
  first_call_input_tokens integer,
  second_call_input_tokens integer,
  first_call_prompt_tokens integer,
  first_call_output_tokens integer,
  first_call_total_tokens integer,
  second_call_prompt_tokens integer,
  second_call_output_tokens integer,
  second_call_total_tokens integer
);

create index if not exists idx_ai_usage_logs_user_id_created_at
  on public.ai_usage_logs(user_id, created_at desc);

alter table public.ai_usage_logs enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'ai_usage_logs'
      and policyname = 'Users can insert their own usage logs'
  ) then
    create policy "Users can insert their own usage logs"
      on public.ai_usage_logs
      for insert
      with check (auth.uid() = user_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'ai_usage_logs'
      and policyname = 'Users can view their own usage logs'
  ) then
    create policy "Users can view their own usage logs"
      on public.ai_usage_logs
      for select
      using (auth.uid() = user_id);
  end if;
end $$;
